### ISSUE TITLE
Unable to save the project once 3D models are imported

### ISSUE THREAD

**Issue by KnightCoder** [tentone/nunuStudio#376]
# Unable to save the project once 3D models are imported

##### Description
 - Opened a new instance of nunuStudio
 - Imported 3D model (.glb file) containing animations
 - Tried to "Save As" the file 
 - It gave error "Error saving file NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'blob:http://localhost/1785a80f-de08-3a58-a879-88b282ad2ed1' " 
 - On console as well I see this error : 

```
nunuStudio: Error saving file DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'blob:http://localhost/1785a80f-de08-3a58-a879-88b282ad2ed1'.
    at Function.FileSystem.readFileArrayBuffer (http://localhost/nunuStudio-master/source/core/FileSystem.js:189:8)
    at Image.toJSON (http://localhost/nunuStudio-master/source/core/resources/Image.js:213:39)
    at Texture.toJSON (http://localhost/nunuStudio-master/source/core/texture/Texture.js:180:23)
    at http://localhost/nunuStudio-master/source/core/objects/Program.js:644:44
    at Program.THREE.Object3D.toJSON (http://localhost/nunuStudio-master/source/core/three/core/Object3D.js:377:3)
    at Program.toJSON (http://localhost/nunuStudio-master/source/core/objects/Program.js:633:45)
    at Function.Editor.saveProgram (http://localhost/nunuStudio-master/source/editor/Editor.js:913:49)
    at http://localhost/nunuStudio-master/source/editor/gui/Interface.js:69:11
    at Function.FileSystem.chooseFileName (http://localhost/nunuStudio-master/source/core/FileSystem.js:526:4)
    at Interface.saveProgram (http://localhost/nunuStudio-master/source/editor/gui/Interface.js:67:14)
```
 - Please note: this doesn't happen with every file however, it happens with most of the imported 3D models.

##### Version
 - 0.9.6

##### Platform
 - Web Version [X]
 - Windows [X]

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this problem i will try to fix it as soon as possible.

Is it possible for you to share one of the files in which your are having this issue?

Thanks  alot

**Comment by KnightCoder** [comment]
You will find the 3D model [here](https://threejs.org/examples/#webgl_animation_skinning_blending)

**Comment by tentone** [comment]
![Capture](https://user-images.githubusercontent.com/9158354/80314808-99770580-87eb-11ea-852b-0a361530aefb.PNG)

Thanks a lot, Fixed in the last version
