### ISSUE TITLE
What are the steps to start / build nunuStudio ?

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#509]
Hello 
I am sorry I can't figure how to launch nunuStudio with the latest source from github. Could you please detail what "npm" commands I need to type in order to either build or start nunuStudio (on linux) ?

Or even better do you plan to update the released binaries ? I haven't tried the other platforms but the one for Linux seems very outdated (2019!) . But beside being outdated it works well and it is very easy to launch. That would be great if we could have the latest build released !

**Comment by tentone** [comment]
Hello

To build the code you will need to run these three commands.

Some of the deps are not present in npm so i have added napa to handle these.

```
npm install
npm install napa
npm run build
```


Thanks a lot!

**Comment by shantee** [comment]
Sorry to bother it still doesn't work
Everything goes well until I run 
`npm run build` 
it gives me this error
```

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/zfx/logiciels/nunuStudio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/zfx/logiciels/nunuStudio/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/zfx/logiciels/nunuStudio/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/zfx/logiciels/nunuStudio/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/zfx/logiciels/nunuStudio/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/zfx/logiciels/nunuStudio/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/zfx/logiciels/nunuStudio/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/zfx/logiciels/nunuStudio/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/zfx/logiciels/nunuStudio/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/zfx/logiciels/nunuStudio/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/zfx/logiciels/nunuStudio/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0

``` 
I suppose I will have to try on an other machine with a fresh node/npm install unless you have a solution ?

May I ask why don't you put a prebuilt version on nunuStudio website ? The builts available seem very far behind the latest branch of nunustudio.

**Comment by oneWaveAdrian** [comment]
@shantee Readme says you gotta use Node LTS which is currently version [`16.15`](https://nodejs.org/en/). You used `v17.3.0` I assume some dependencies fail here.
